<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            'BIOSTAR B450M MOTHERBOARD',
            'MODEM FTTH UNO F680C',
            'NComputing-MX100S',
            'NETWORKING EQUIPMENTS FOR JAILGLENS NET WIRELESS',
            '1.2 FBT SPLITTER 10/90 NO CONNECTOR',
            '1.2 FBT SPLITTER 15/85 NO CONNECTOR',
            '1.2 FBT SPLITTER 15/85 WITH CONNECTOR',
            '1.2 FBT SPLITTER 20/80 NO CONNECTOR',
            '1.2 FBT SPLITTER 25/75 NO CONNECTOR',
            '1.2 FBT SPLITTER 30/70 NO CONNECTOR',
            '1.2 FBT SPLITTER 35/65 NO CONNECTOR',
            '1.2 FBT SPLITTER 40/60 NO CONNECTOR',
            '1.2 FBT SPLITTER 45/55 NO CONNECTOR',
            '1.2 FBT SPLITTER 5/95 NO CONNECTOR',
            '1.2 FBT SPLITTER 90/10 NO CONNECTOR',
            '1.2 FBT SPLITTER50/50 NO CONNECTOR',
            '12V 4X4 blowervfan',
            '24 CORE FIBER BOX[EMPTY]',
            'A4TECH KEYBOARD ONLY',
            'A4Tech Mouse And KeyBoard KRS-8372',
            'A4Tech Mouse USB 1000DPI',
            'Ado Business',
            'AdoLite',
            'Akina Vendo Sticker',
            'Akina Vendo Tarpaulin',
            'AMD 3200g Athlon',
            'AMD A6-7480 3.8Ghz, 1MB cache',
            'AMD RYZEN ORIGINAL HEATSINK FAN',
            'AMD Ryzen3 3200G',
            'ANCHOR TENSION CLAMP',
            'Armoured mini figure-16core 2km',
            'Armoured mini figure-24core 2km',
            'ASUS PRIME A320M-K DDR4 AM4 AVL',
            'ASUS PTIME A520M-K MOBO',
            'AVR 500W 220V',
            'Awifi',
            'BLOWER FAN METAL COVER 12MM',
            'BNC-Spring Male {Silver }',
            'BRIDLE RING',
            'Buck Converter 5v 5a',
            'Cable jacket slitter 1.5-3.3mm',
            'CAMERA HIKVISION DS-2CD1027G2-L (2.8mm) 2MP BULLET',
            'CAMERA HIKVISION DS-2CD1327G2-L (2.8mm) 2MP DOME',
            'CARD READER LENOVO 2TB D231',
            'Case with Fan  OPI One',
            'Case with Fan OPI PC',
            'Case with Fan RPI',
            'CASELESS TRAY',
            'CASH ADVANCE',
            'CASING WITH POWER SUPPLY/FAN (INPLAY)',
            'CCTV INSTALLATION AND MATERIALS',
            'CCTV JUNCTION BOX WATERPROOF WHITE',
            'CFS-3 Three fiber miller stripper',
            'CH028-24 HORIZONTAL FIBER TYPE SPLICE CLOSUER 24 CORE',
            'CMOS BATTERY',
            'Coin Selector RGB led frame',
            'Coindoor SIngle Butas',
            'Coinslot',
            'Comfast CF-8317A 5Ghz',
            'Comfast CF-E314N V2',
            'Comfast CF-EW71',
            'Comfast CF-EW73',
            'Comfast CF-EW81 Outdoor AP 300mbps VLAN 3Port (High Power)',
            'Comfast CF-EW85,Outdoor AP 1300Mbps, VLAN 3port High Power',
            'Comfast CF-N1 Wireless router | bandwidth control',
            'Comfast Wifi Dongle',
            'COMLINK (Per Meter) V3 1B(1KM) FIBER DROP CABLE {PREMIUM} 1.2mm /3 steel GJYXCH galvanized',
            'COMLINK 1 CORE(2KM) FIBER DROP CABLE {PREMIUM} GJYXCH galvanized',
            'COMLINK 12B(2KM) MINI FIG 8 CABLE GALVANOZED{PREMIUM}GTXTCBY',
            'COMLINK 1DC6-A100 INDOOR CAT6 UTP CABLE 100M',
            'COMLINK 2B(1KM) FIBER DROP{PREMIUM}',
            'COMLINK 2f(2KM) FIBER DROP CABLE {PREMIUM} GJYXCH 1.2mm/3 steel galvanized',
            'COMLINK 4B(2KM) MINI FIG 8 CABLE GALVANOZED{PREMIUM}GTXTCBY',
            'COMLINK 4CORE(2KM) FIBER DROP CABLE {PREMIUM} GJYXCH galvanized',
            'COMLINK 8B(2KM)MINI FIG 8CABLE GALVANIZED{PREMIUM} GYXTC8Y',
            'Comlink BNC-DC Premade Cable 30M',
            'COMLINK C60D-A010, OUTDOOR CAT6 UTP CABLE PATCH CORD 10M,CCA',
            'COMLINK CCTV JUNCTION BOX 65*65*50MM',
            'COMLINK COXIAL-POWER SIAMESE CABLE RG6/ CCS',
            'COMLINK DROP CABLE 4F (2KM) Galvanized',
            'COMLINK FIBER LADDER',
            'COMLINK Fiber Media Converter (1000mbps)',
            'COMLINK Fiber Media Converter (100mbps)',
            'Comlink Flat Cord #16AWg 150M\\Roll',
            'Comlink Flat Cord #16AWg 150M\\Roll per meter',
            'COMLINK GLOBE Mini Fig 8 12F(2km) 1.8mm Steel GYXTBC8Y- 12CORE',
            'COMLINK GLOBE Mini Fig 8 16f (2km) 1.8mm Steel GYXTBC8Y- 16CORE',
            'COMLINK HTB-3200AB-SFP DUAL MEDIA CONVERTER WITH SFP SC MODULE',
            'COMLINK OUTDOOR CAT6 UTP CABLE PATCH CORD 3.M CCA',
            'Comlink Outlet 3Gang',
            'COMLINK ROUTER 5V5',
            'COMLINK USB 3.0 ETHERNET ADAPTER 10/100/1000MBPS',
            'COMLINK V2 Armoured Mini Fig 8 12F(2km) 1.5mm GYXTC85 12CORE',
            'COMLINK V3 1B(1KM) FIBER DROP CABLE {PREMIUM} 1.2mm /3 steel GJYXCH galvanized',
            'COMPUTER SET',
            'Crimping tool Pass Through',
            'CRIMPPING TOOL REGULAR',
            'CUSTOM BOARD-LANBASE',
            'CUSTOM BOARD-WIRELESS',
            'Dahua DH-HAC-B1A21N 3.6MM 2MP HDCVI IR BULLET CAMERA',
            'Dahua DH-HAC-HDW1239TLMN-A (bullet Full Color)',
            'Dahua DH-HAC-HDW1239TLQN-A (Dome Full Color)',
            'Dahua DH-HAC-T1A21N 3.6MM 2MP HDCVI IR EYEBALL CAMERA (DOME)',
            'Dahua DHI-NVR4108HS-4KS2/L (8 Channel Compact 4K&H.265 Lite Network Video Recorder)',
            'DAHUA DHI-NVR4416-4KS2/I 16 Channel 1.5U 4HDDs WizSense NVR',
            'Dahua DH-IPC-HDPW1431R1N-S4 4MP IR DOME NETWORK CAMERA',
            'Dahua DH-IPC-HDW1239T1N-LED-S5 3.6MM (2MP LITE FULL COLOR EYEBALL NETWORK CAMERA)',
            'Dahua DH-IPC-HDW2431TN-AS 4MP Dome FullColor',
            'Dahua DH-IPC-HFW1230S1 3.6MM (2MP IR MINI-BULLET NETWORK)',
            'Dahua DH-IPC-HFW1230T1 3.6MM (2MP IR MINI-DOME NETWORK)',
            'Dahua DH-IPC-HFW1239S1N-LED-S5 3.6MM (2MP LITE FULL COLOR BULLET NETWORK CAMERA)',
            'Dahua DH-IPC-HFW1431SN-S4 WDR IR Bullet Camera- All metal Case',
            'Dahua DH-IPC-HFW2439MN-AS-LED 4MP Bullet FullColor',
            'DAHUA DH-KIT-CVI2MP2B2D-FC (4 CHANNEL KIT COLORED AITH AUDIO)',
            'Dahua DH-NVR5216-4KS2 16CH 2HDD NVR',
            'Dahua DH-PH-KIT/XVR1B04 (4 Channel 1 SATA)',
            'Dahua DH-PH-KIT/XVR1B08 (8 Channel 1 SATA)',
            'Dahua DH-SD59430UN-HNI 4MP 30X Starlight PTZ',
            'Dahua DH-XVR1b16-I (16 CHANNEL PENTA BRID 1080N/720P COMPACT 1HDD WIZ SENSE)',
            'DAHUA DH-XVR4108HS- I(US)',
            'Dahua DH-XVR5108HS-I3',
            'DAHUA DVR -DH-XVR1B04-I (4 CHANNEL)',
            'DAHUA DVR -DH-XVR1B08-I /T (8 CHANNEL)',
            'DAHUA DVR-8 CHANNEL',
            'DAHUA-HAC-HFW1239CN 2.8',
            'Data Cabinet (15U)',
            'Data Cabinet (4U) 600*450*300 wall mountable',
            'Data Cabinet (6U 600X) 450mm Mesh front door GTT6u',
            'Data Cabinet (9U) Glass',
            'Data Cabinet (9U) Mesh',
            'Data Cabinet 12U (600x600)',
            'Data Cabinet 27U (600x600)',
            'Data Cabinet 32U (600x600)',
            'Data Cabinet 42U (800x800)',
            'Data Cabinet 42U Floor Mounted (600x1000) Single rear door',
            'Data Cabinet 42U Floor Mounted(600x1000) Double Rear Door',
            'Data Cabinet 42U Floor Mounted(600x800)Double Rear Door',
            'Data Cabinet 42U Floor Mounted(600x800)Single rear door',
            'DC Jack female',
            'DC-21 MALE',
            'DH-HAC-HFW1239CN-A-LED S3.3.6MM',
            'DHI-NVR4116HS-4KS3{US',
            'DHI-NVR4232-4KS3',
            'DH-IPC-B1820.E3.6MM/BULLET IR',
            'DH-IPC-B1A20-E',
            'DH-IPC-T1A20.E3.6MM/DOME IR',
            'DH-IPC-T1A20-E',
            'DH-PFM320-US-S (DC12V2A) ADAPTER',
            'DH-PFM800-4K 1CH PASSIVE VIDEO BALUN',
            'DH-PFM920-6UN (BLACK CU-OUT)',
            'DH-PFS3010-8ET-65',
            'DH-XVRIB08-I(US) 8CHANNEL PENTAL-BRID 1080N/720P COOPER 1U1HDD WIZSENSE DIGITAL VIDEO RECORD',
            'D-LINK 16 Port  Desktop Switch (Non-gigabit)',
            'D-LINK 16 Port Gigabit Unmanaged Switch',
            'DS-2CD1047G2-L (2.8mm)',
            'DS-2DE4225IW-DE (T5) with brackets 4-inch 2 MP 25X',
            'DS-3E0510P/M8 ORT GIGABIT UNMANAGED POE SWITCH',
            'DS-3E1526P-SI24 PORT GIGABIT WEB POE SWITCH',
            'DS-7732NXI-I4/16P/S 32-ch 1.5U 16 PoE AcuSense 4K NVR',
            'DS-E3E0518P-EI/M 16 PORT GIGABIT UNMANAGED POE SWITCH',
            'DUPONT WIRE',
            'DynaBook Satelite B554/M',
            'ELECTRIC BLOWER 800W',
            'ELECTRON PSU 700W BLACK',
            'EPSON L3210 5760x 1400 DPI Print Scan Copy',
            'Extension Ladder 20ft',
            'Extension Ladder 24ft',
            'F010 Fiber Optic Closure 2 in 2 out 96core (4plate,24 core/plate)',
            'F101H Fiber Optic Splice Joint box (Closure) Dome 24 core',
            'F211 EMPTY BOX ACCESSORIES [2PCS HOOP+2PCS POLE BRACKET MATERIAL:ABS COLOR:WHITE',
            'F211 FTTH Box 24 cores Empty Box  (WHITE)',
            'F215 FIBER OPTIC BOX 16 cores (2 in 16 out) PLC empty Box (BLACK)',
            'F311 Fiber Optic Termination box 4 core empty',
            'F408B-12C FIBER OPTICAL PATCH PANEL-1U',
            'F408B-24C Fiber Optical Patch Panel -1U',
            'F408B-48C Fiber Optical Patch Panel -1U',
            'F6610M MODEM WIFI6',
            'FAN 12mm',
            'Fiber Cable 2000M Single Core',
            'FIBER CLAMP',
            'Fiber Cleaner SC Pen type',
            'Fiber Cleaver Precision type',
            'Fiber distribution Box # 1',
            'FIBER DROP CABLE 1KM 1 CORE (butterfly optical fiber cable) 1.2mm',
            'FIBER DROP CABLE 1KM 1 CORE (Galvanized) 1.0mm',
            'FIBER DROP CABLE 1KM 1 CORE (Non-galvanized) 1.0mm',
            'FIBER DROP CABLE 1KM 1 CORE 1.0mm (per mtr)',
            'FIBER DROP CABLE 2KM 1 CORE (galvanized) 1.0mm',
            'FIBER LADDER 28FT',
            'Fiber Optic Patch Cord SC-SC',
            'FIBER OPTICAL CABLE 3.0 1.5Meters',
            'FIBER OPTICAL CABLE 3.0 3Meters',
            'FIBER OPTICAL CABLE 3.0 5Meters',
            'Fiber Roller Rack Foc 50cm x34cm',
            'Fiber Tool Kit',
            'Fiber white color Protection Box',
            'FIVER OPTICAL CABLE 3.0.10M',
            'FLASH DRIVE-SANDISK CRUZER BLADE USB 2.0 -128GB',
            'FLASH DRIVE-SANDISK CRUZER BLADE USB 2.0 -16GB',
            'FLASH DRIVE-SANDISK CRUZER BLADE USB 2.0 -32GB',
            'FLASH DRIVE-SANDISK CRUZER BLADE USB 2.0 -64GB',
            'Flat cord',
            'FORMECA ASSORTED COLORS',
            'FTECH LICENSE',
            'FTTH Box Hole Bracket',
            'FUSHION SPLICER MACHINE DVP 765',
            'Gen 2',
            'Gen2 Prism',
            'Genius Mouse',
            'GK10 MICROPACK GAMING KEYBOARD',
            'GOLD PLAN (100 MBPS)',
            'Grills',
            'H LOCK',
            'HARD DRIVE 16 TB- ST16000NM002H',
            'HARD DRIVE ST8000VX004 (8TB)',
            'HARD DRIVE SURVEILLANCE WD PURPLE 1TB',
            'HARD DRIVE Surveillance WD PURPLE 3.5 4TB HDD',
            'HARD DRIVE SURVEILLANCE WESTERN DIGITAL PURPLE 2TB',
            'HDMI CABLE',
            'HDMI TO VGA FEMALE',
            'Heatsink OPI ONE/PC',
            'Heatsink RPI',
            'HIKVISION 4 CHANNEL KIT V1-4CH2D2B-2MP-ECO',
            'HIKVISION 8 CHANNEL COLORVU KIT',
            'HIKVISION 8 CHANNEL KITV1-8CH4D4B-2MP-ECO',
            'HIKVISION DS-2CE56D0T-IRPF (3.6MM)',
            'HIKVISION DS-2CE56D0T-IRPF (camera)',
            'HIKVISION DVR- 8 CHANNEL 7208hghi-m1',
            'Hikvision DS-2CD1047G2-LUF (2.8mm)- Bullet 4mp with Audio',
            'Hikvision-HDMI DS-7700 Series EmbeddedNVR',
            'Hikvision-TVI-8CH4D4B-2MP-ECO',
            'HKC PC DDR4 8GB 2666MHZ WITH HEATSINK',
            'HKC SHADWWING D5600 2.5 SATA SSD 256G',
            'Hookup Wire 10meters',
            'Hookup Wire 150M/Roll',
            'HP-19V 4.62A Laptop charger',
            'HTB-G582 ENTERNET FIBER SWITCH GIGABIT 8PORT',
            'HYBRID ANTENNA',
            'HY-PSU1210-09C 220 VAC INPUT 12VDC 10A-9CH INDIVIDALLY',
            'HY-PSU1220-18C',
            'Inplay 450W TrueRated PSU',
            'Inplay 650W TrueRated PSU',
            'Inplay 750W Generic Small Fan PSU',
            'Inplay Clear HD Sounds Noise Cancelling Headset',
            'Inplay Computer case Lite x220- WHITE',
            'Inplay GS250BK 250W',
            'INPLAY GS750 ULTRA RATED 750W POWER SUPPLY / RGB 80PLUS BRONZE',
            'INPLAY H2 HEADSET',
            'INPLAY H20 RGB HEADSET ASSORTED COLORS',
            'INPLAY JADE TOWER X3 3-IN-1 ARGB FAN KIT',
            'Inplay M10 Rainbow RGB Air Fan',
            'INPLAY M10-RGB DUAL RING 12CM LED CASE FAN 4PIN SATA 55',
            'INPLAY METEOR 03 MID-TOWER PC CASE/WHITE',
            'INPLAY METEOR 30 MID-TOWER PC CASE/ WHITE',
            'INPLAY MOUSE M360 USB MOUSE',
            'Inplay POWER SUPPLY 250W  GENERIC 800W',
            'Inplay STX 200 Mouse & Keyboard',
            'Inplay STX360 KB & Mouse Bundle- BLACK',
            'Inplay STX380Pro Keyboard Mouse Bundle White Grey Mix',
            'INPLAY STX540 4 IN ONE COMBO/BLACK',
            'INPLAY UFO RGB FAN 3PCS KIT',
            'Inplay WeB Camera HD1080P',
            'Inplay WeB Camera HD720P',
            'Inplay X1 Case with PSU',
            'INTEL ORIGINAL HEATSINK FAN FOR 12.13TH GEN',
            'INTERNET BILL (APRIL 10,2024-MAY 10,2024)',
            'INTERNET BILL -GATUNGAN',
            'INTERNET BILL INCOME REMITTED',
            'INTERNET BILL- KITOLAO',
            'INTERNET BILL -MAHAYAG',
            'INTERNET BILL -PUROK 2',
            'INTERNET BILL -QUITOLAO',
            'INTERNET BILL-KIOTOY',
            'INTERNET BILL-MADUAO',
            'INTERNET BILL-MATARLO',
            'INVISION TV 42 inch',
            'JEDEL MOUSE & KEYBOARD COMBO G10',
            'JUANFI CUSTOM BOARD',
            'Jumper Wire',
            'K203 MICROPACK WIRED KEYBOARD',
            'KINGSTON PC DDR4 8G 2666MHZ LONGDIIMM',
            'KINGSTON RAM DDR4 8GB FURY',
            'KINGSTON- RAM DDR4 8GB FURY',
            'kitifi credits/sub vendo',
            'Kitifi Custom board',
            'kitifi license',
            'L300 (REPAIR AND MAINTENANCE)',
            'Labor (Assemble Pisonet)',
            'Labor (Assemble Vendo)',
            'LAN MODULE',
            'LAN Network Cable Tester',
            'Lap 120',
            'Lap GPS',
            'LAPTOP 15.6 INCHES/SURPLUS CHARGER/SURPLUS RAM.DDR3 4GB',
            'Laptop Charger Asus',
            'LCP SPLITTER CASSETE BOX WITH PIGTAIL 1X8',
            'Led Lights',
            'Logitech MK120 Mouse & Keyboard',
            'L-TYPE BOARD SPACER 20MM {50PCS/PACK}',
            'Male DC Plug {1PC} with terminal screws',
            'male plug',
            'maxsun A320 Mother Board',
            'Media Converter Set A-B Gigabit',
            'MEP Hotsport License',
            'Mikrotik 1.25G SFP TRANSRECEIVER UP TO 20KM SINGLE MODE',
            'MIKROTIK CCR2004 16GB 28+/8N HEV0531HE3K',
            'MIKROTIK CCR2116- 12G-41 0G',
            'Mikrotik Crs317-1g-16s@',
            'Mikrotik Haplite',
            'Mikrotik HEX GR3',
            'Mikrotik RB5009UG+S+IN',
            'Mikrotik Router CCR1009-7G-1C1S',
            'Mikrotik Router RB4011GS RM',
            'MIKROTIK-CRS326-CRS326-24G-2S24 GIGABIT PORT SWITCH',
            'Mimosa 1 N5-X25 c5X cassegrain Antenna 25 DBi 40,DB F/S',
            'Mimosa C5X With POE 700mbps Max PTMP/PTP[IP] Throughput 8-25dbi Gain 4,9-6,4GHZ Extended Frequency',
            'MINI FIGIRE-OPTIC FIBER CABLE GYXTC8Y-12F G652D',
            'MINI FIGIRE-OPTIC FIBER CABLE GYXTC8Y-8F G652D',
            'MODEM ECOM TERMINAL H66821M-2 ANTENNA',
            'MODEM ECOM TERMINAL H66821M-4 ANTENNA',
            'MODEM Hioso TERMINAL H66821M-2 ANTENNA',
            'MODEM Hioso TERMINAL HG6821M-4 ANTENNA',
            'MODEM ONU TERMINAL F670L-2 ANTENNA',
            'MODEM WIFI - 6 China Mobile (Refurbished)',
            'MODEM WITH GOMO SIM',
            'Mother Board Biostar A320 & Ryzen3 3200G',
            'Mother Board Biostar A320 &A12-8870',
            'MSI A520-A PRO MOBO',
            'MW301R Mercusys 300MBPS Wireless N-Router 1 10/100 Wan',
            'MW325R Mercusys 300MBPS Enchanced Wireless N Touter',
            'N350 MICROTECH N350 COMPUTER SPEAKER',
            'NAPBOX COMLINK -OTB - 0216-CP16-UPC CASETTE SPLITTER 1:16 SC/UPC W ITH PIGTAIL &CALMP PARTS',
            'NIIMBOT B1 LABEL MAKER',
            'NK1000D OTDR Optical fiber tester Dual band',
            'NODEMCO',
            'nodemco C-B',
            'NOVKER NK3200D OTDR OPTICAL FIBER TERBER DUAL BAND',
            'NOVKER NK4000D OTDR OPTICAL FIBER TERBER DUAL BAND',
            'Nvision 40 inch Led  Monitor',
            'Nvision H22V8 21.5 LED MONITOR',
            'Nvision N190HD 19 Led 60Hz Monitor',
            'Nvision N190HD20 Led  Monitor',
            'NVISION N2255PRO-B 21.5 FHD@ 100HZ IPS MONITOR/FRAMELESS/BLACK',
            'Nvision N2455 PRO-B23.8 FRAMELESS BLACKC IPS Monitor',
            'N-VISION P215FHD 2.1FHD LED MONITOR',
            'N-VISION TV 32 INCH SMART LED TV',
            'NVR- DS- 7732NXI- K4 32 CHANNEL',
            'OLD LIST OF CREDIT',
            'omni 4gang outlet',
            'OPI Cord',
            'optical fiber machine',
            'Optical Power Meter',
            'Orange Pi one (1gb)',
            'Orange Pi One Custom Board',
            'Orange PI PC',
            'Orange Pi Zero3 1Gb Ram Type C. Port',
            'OTDR LAUNCH CABLE 1KM',
            'Others/Materials',
            'PAD LOCK',
            'PATCH PANEL 24PORT CAT5e',
            'PATCH PANEL 48PORT CAT5e',
            'Pisofi License',
            'Pisonet Box',
            'PisoWifi (000316) -OPI One- Small Box-Pull out (field)',
            'PisoWifi (000342) -OPI One- Small Box, with Custom Board) 5A',
            'PisoWifi (000381)-OPI One- Small Box, with fan    5A',
            'Pisowifi Box',
            'Pisowifi Box (Big)',
            'PisoWifi CENTRALIZED-JUANFI- Small Box, with Custom Board) 5A',
            'PLC SPITTER 1X8 FBT TYPE 95/5',
            'PLC SPLITTER 1X16 FBT TYPE 50/50',
            'PLC SPLITTER 1X16 FBT TYPE 60/40',
            'PLC SPLITTER 1X16 FBT TYPE 70/30',
            'PLC SPLITTER 1X16 FBT TYPE 80/20',
            'PLC SPLITTER 1X16 FBT TYPE 90/10',
            'PLC SPLITTER 1X16 FBT TYPE 95/5',
            'PLC SPLITTER 1X8 FBT TYPE 50/50',
            'PLC SPLITTER 1X8 FBT TYPE 70/30',
            'PLC SPLITTER 1X8 FBT TYPE 75/25',
            'PLC SPLITTER 1X8 FBT TYPE 80/20',
            'PLC SPLITTER 1X8 FBT TYPE 85/15',
            'PLC SPLITTER 1X8 FBT TYPE 90/10',
            'PLC SPLITTER 1X8 FBT TYPE 95/5',
            'PLC SPLITTER UPC 1:4',
            'PLC SPLITTER UPC 1:8',
            'POE Adapter 24v 5a(Gen2)',
            'POE ADAPTER 48V (Comfast)',
            'Portable HDD StoreJet 25M3 USB 3.1 Gen 1 1TB',
            'Power Adapter 12v 5a',
            'POWER ADAPTER- EW85',
            'POWER SUPPLY (CENTRALIZED )DC 12V/5A ALUMINUM CASE',
            'POWER SUPPLY WITH CASE-HY-PSU1220-18C (20A)',
            'PREMIUMLINE PATCH CORD 1M-BLUE',
            'PROCESSOR INTEL I3 I2100/ ASUS H610-K-MOBO (BUNDLE)',
            'PROCESSOR INTEL I7 10700/GIGABYTE H510DM-K MOBO',
            'PROCESSOR RYZEN 5 4600G',
            'PSU 12V 5A adapter',
            'Push button',
            'RAMSTA 5800 SATA SSD 128GB|2.5',
            'RAMSTA r5-B450MP MOBO',
            'RAMSTA RB-850 80PLUS BRONZE FULL MMODULAR 850W GAMING POWER SUPPLY',
            'RAMSTA S800 SATA SSD 512/2.5',
            'RESET CABLE',
            'RETRACTOR',
            'Reyee RG-EW3000GX, AX3000 Wi-Fi 6 Dual-Band Gigabit Mesh Router',
            'Reyee RG-RAP52-OD, AC1300 Dual Band Gigabit Wireless AP',
            'RG ES116G-L 16 PORTS GIGABIT UNMANAGED SWITCH 16 GIGABIT',
            'RG-AP820-L(V2)',
            'RG-E-120(GE)(PSU for RG-AP820-L(V2))',
            'RG-M000E-DC500P DC POWER MODULE 32VDC TO 72VDC',
            'RG-M5000E-AC500P AC POWER MODULE, 370W POWER BUDGET FOR POE',
            'RG-PA1150P-F AC POWER MODULE 740W POWER BUDGET FOR POE',
            'RG-S2910C-24GT2XS-HP-E (24PORT 10/100/1000 BASE',
            'RG-S2910C-48GT2XS-HP-E 48PORT 10/100/1000 BASE',
            'RJ45 Plastic Type (passthrough)',
            'RPI 4 Computer Model B 2GB RAM',
            'RPI Cord',
            'RUBBER CAP COMLINK: RC-CAP 100 RJ45',
            'Ruijie RG-E-120(GE) POE Adapter',
            'Ruijie RG-EAP602 AC1200 Dual Band Gigabit Outdoor AP',
            'Ruijie RG-EAP6262 Wireless AP WiFi6 with adaptor',
            'Ruijie RG-EG105GW 1350M Dual Band 5-Port Gigabit Wireless Router',
            'RUIJIE RG-EG2100-P V2',
            'RUIJIE RG-ES105GD 5-PORT Gigabit Unmanaged Metal Switch',
            'RUIJIE RG-ES108D 8-PORTUnmanaged Switch 10/100 Base',
            'RUIJIE RG-ES108GD 8-PORT [Non Giga] Unmanaged Metal Switch',
            'RUIJIE RG-ES108GD 8-PORT Gigabit Unmanaged Metal Switch',
            'RUIJIE RG-ES205GC-P 5-Port Gigabit Cloud Managed POE+ Switch',
            'RUIJIE RG-ES209GC-P 9-Port Gigabit Cloud Managed PoE+ Switch',
            'RUIJIE RG-ES218GC-P 18-Port Gigabit Cloud Managed PoE+ Switch',
            'Ruijie RG-EW1200 1200M Dual Band 100m Wireless Router',
            'Ruijie RG-EW1200G PRO 1300M Dual Band Gigabit Wireless Router',
            'Ruijie RG-EW1800GX PRO 1800M WIFI 6 Dual Band Gigabit Wireless Router',
            'RUIJIE RG-RAP2200(E) AC1300 Dual Band Gigabit Ceiling Mount Access Point',
            'RUIJIE RG-RAP2260(G) AX1800 Dual Band Gigabit Ceiling Mount Access Point(wifi6)',
            'RYZEN 5 3400G WITH ASUS 520M MOBO  (BUNDLE)',
            'RYZEN 5 4650G WITH BIOSTAR A520 MOBO',
            'RYZEN3 3200G BUNDLE..KINGSTONE 8GB DDR4.ASUS BOARD 480GB RAM KINGSTONE',
            'SANDISK MICRO SD CARD 128gb',
            'SANDISK MICRO SD CARD -64GG',
            'SANDISK Micro SDHC UHS-1 Card 16 GB',
            'SANDISK Micro SDHC UHS-1 Card 32GB',
            'SATA CABLE',
            'SC -UPC Fiber Adaptor',
            'SC-UPC CONNECTOR (BUTTERFLY TYPE)',
            'SEAGATE BARRACUDA 500GB',
            'SEAGATE HARD DRIVE 1TB',
            'Seagate ST4000VX000 4TB HDD',
            'SECURE AVR',
            'SERVICE-LABOR: INSTALLATION/MOBILIZATION',
            'SIAMESE CABLE -POSCOM-30M-1',
            'Siamese Cable-RG-6 300M',
            'SKIHOTAR PC DDR4 4G 2666 MHZ',
            'SKIHOTAR PC DDR4 8GB 3200MHZ',
            'SkyHawk Surveillance  2TB',
            'Small Mouse Pad',
            'Solid State Drive Maxsun SSD 240Gb',
            'SOlid-State Drive Kingston 480gb',
            'SOlid-State Drive Ramsta 120GB',
            'SOlid-State Drive Ramsta 240GB',
            'SPLITTER UPS 1:16 WITH PIGTAIL',
            'SPLITTER WITH PIGTAIL 1:2',
            'SPLITTER WITH PIGTAIL 1:4',
            'SPLITTIR 1.8 UPC WITH PIGTAIL',
            'SSD RAMSTA 256 GB',
            'ST4000VX000',
            'ST4000VX01/4TB',
            'STAINLESS STEEL BUCKLES 1/2',
            'STAINLESS STELL 5/8 100FT/30.05M PER ROLL',
            'Step Down 5v 3a',
            'TELESCOPE HOT STICKS 4*6M',
            'Tenda A9 300MBPS WIRELESS RANGE EXTENDER',
            'Tenda AC11',
            'TENDA AC6 1200MBPS SMART DUAL BAND',
            'TENDA CH3 OUTDOOR FULL COLOR 1080',
            'TENDA CH9,6MP DUAL LENS LINKAGE OUTDOOR PAN/TILT WIFI CAMERA',
            'Tenda CP3 SECURITY CAMERA PAN/TWO WAY AUDIO 3MP PRO',
            'TENDA CP7 CAMERA',
            'TENDA F3 300MBPS WIRELESS ROUTER',
            'Tenda F6',
            'TENDA OAP1200 AC1200 GIGABIT OUTDOOR',
            'Tenda S105 5PORT ETHERNET SWITCH 10/100MBPS',
            'TENDA S105 8PORT RTHERNET SWITCH 10/100MBPS',
            'Tenda SG105 5PORT GIGABIT DESKTOP SWITCH',
            'Tenda SG108 8PORT GIGABIT DESKTOP SWITCH',
            'Tenda W18E Dual Band',
            'Tenda: 09',
            'TENSIONING TOOL',
            'THERMAL PASTE INJECTIO0N TYPE',
            'TIMER',
            'TL-SF1016 D-16-Port 10/100Mbps Desktop Switch-NON GIGABIT',
            'Toshiba 3.5 surveillance s300 1TB',
            'TOSHIBA3.5 Surveillance S300 2TB',
            'TP Link LS1008 8-port Non-gigabit switch',
            'TP Link TL-SG1008D 8PORTS',
            'TP Link TL-SG1024D 24 Port Gigabit',
            'TP Link TL-SG105 5PORTS GIGABIT SWITCH METAL TYPE',
            'TP Link TL-WR840N',
            'TP-Link  EAP110-Outdoor WiFi A/P',
            'TP-Link  EAP225-Outdoor WiFi A/P',
            'TP-Link EAP610 Outdoor AX1800 Indoor/Outdoor WiFi 6 Access Point',
            'TP-Link ER7212PC Omada 3-in-1 MultiWan+POE+Omada Controller Gigabit VPN Router',
            'TPLINK LS1005 5PORT 10/100MBPS DESKTOP SWITCH',
            'TPLINK LS1008 8PORTS 10/100MBPS SWITCH',
            'TP-LINK OMADA OC200',
            'TPLINK SG1016D 16PORT GIGABIT SWITCH',
            'TP-LINK TAPO C100 HOME SECURITY WIFI CAMERA',
            'TP-LINK Tapo C310 Outdoor Security Wi-Fi Camera',
            'transformer 12v  Pisonet',
            'Ubiquiti LBE M5 23',
            'Ubiquiti NANO STATION M2',
            'UPS 1000va',
            'UPS-650VA',
            'USB to LAN Adapter 3.0',
            'UTP CABLE CAT6 (Outdoor 305M)',
            'UTP CABLE CAT6(indoor 305M)',
            'UTP Cable per meter (indoor)',
            'UTP Cable per meter (Outdoor)',
            'UTP CABLE PURE COPPER CAT6 (Outdoor 305M)',
            'VECHICLE AND FUEL',
            'VECHICLE RENT (L300)',
            'VGA Cable Computer',
            'VSOL 9DMB PX20++EPON SGP MODULE',
            'VSOL HG323RGW 1GE+1POTS+WIFI ONU',
            'Vsol V1600D4-DP-2AC GEPON OLT 4Port With PX++++ SFP 9dbm*4',
            'Vsol V1600G0-B-2AC GPON OLT 4Port With C++++ SFP 9dbm*4',
            'VSOL V1600GS GPON OLT 1PortIBuilt in GPON SFP Module',
            'WALL MOUNT DATA CABINET 12U 600X600MM MESH FRONT DOOR GTT12U',
            'WIFI-6 F6510M XPON',
        ];

        $now = now();

        // Chunk inserts for performance
        $chunks = array_chunk($names, 50);
        foreach ($chunks as $chunk) {
            $rows = array_map(fn(string $name) => [
                'name'                => $name,
                'sku'                 => null,
                'barcode'             => null,
                'description'         => null,
                'category_id'         => null,
                'cost_price'          => 0,
                'selling_price'       => 0,
                'stock_quantity'      => 0,
                'low_stock_threshold' => 10,
                'is_assembled'        => false,
                'is_component'        => false,
                'has_warranty'        => false,
                'warranty_months'     => null,
                'is_active'           => true,
                'tax_rate'            => 0,
                'is_vat_exempt'       => false,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], $chunk);

            // Insert only if no product with that exact name exists yet
            foreach ($rows as $row) {
                DB::table('products')
                    ->where('name', $row['name'])
                    ->exists() ?: DB::table('products')->insert($row);
            }
        }
    }
}
